project:
  type: website
  output-dir: "../docs"

website:
  title: "<img src='images/headerimage.png' alt='DHW Logo' height='75' style='margin-top:-6px;'>"
  navbar:
    background: dark
    foreground: light
    left:
      - text: About
        menu:
          - text: About D3HW
            href: about.qmd
          - text: Contact
            href: contact.qmd
      - text: Code
        menu:
          - text: Data extraction
            href: data-processing.qmd
          - text: Data visualisation
            href: data-d3.qmd
    right:
      - icon: github
        href: https://github.com/marine-ecologist/dhw3/
        aria-label: GitHub

format:
  html:
    theme:
      - darkly
      - theme-dh3w.scss
    toc: true
    code-fold: true
